"use client";
import { AppContextWrapper } from "./context/AppContext";
// import { Inter } from "next/font/google";
import "./globals.css";
import { MoralisProvider } from "react-moralis";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <MoralisProvider initializeOnMount={false}>
      <html lang="en">
        <AppContextWrapper>
          <body>{children}</body>
        </AppContextWrapper>
      </html>
    </MoralisProvider>
  );
}
